//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webwinkel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersOrdersNOCON
    {
        public int CustomerID { get; set; }
        public int OrdersID { get; set; }
    }
}
