//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webwinkel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersArticle
    {
        public int OrdersID { get; set; }
        public int ArticlesID { get; set; }
        public Nullable<int> AmountArticles { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Order Order { get; set; }
    }
}
